apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nginx-simple-docker
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'nginx-simple-docker:latest'
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/satishbabu/nginx-docker.git'
    type: Git
  strategy:
    dockerStrategy:
    type: Docker
