kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "nginx-simple-docker"
  namespace: sp
spec:
  template: 
    metadata:
      labels:
        name: "nginx-simple-docker"
        deploymentconfig: nginx-simple-docker
    spec:
      containers:
        - name: "helloworld"
          image: >- 
            172.30.1.1:5000/sp/nginx-simple-docker@sha256:b63d35ff017ebe86af06e629aa6d796945fe6574346835b06dd5a7f77097c45b
          ports:
            - containerPort: 8080
              protocol: "TCP"
  replicas: 1
  strategy: 
    type: "Rolling"
